
-- #######################################################################################
-- HYPRLAND LUA CONFIG 
-- Ref: https://wiki.hypr.land/Configuring/Start/

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 # remove this line to remove the warning


--  You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:

require("monitors")
require("env")
require("general")
require("exec")
require("battery")
require("whatsapp")
require("keybinds")
require("rules")
 

