##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = true
}

# Spotify
windowrule {
    name = spotify-float
    match:class = spotify

    float = true
    size = 1200 700
    center = true
    no_anim = false
    no_blur = false
    pin = false
    stay_focused = false
    opacity = 0.8
}

# Float Kitty
windowrule {
    name = kitty-float
    match:class = kittyfloat

    float = true
    size = 1000 600
    center = true
}

# Float Kitty TTY
windowrule {
    name = kitty-float-tty
    match:class = kittyfloat1

    float = true
    size = 400 175
    move = 50 50
}

# Whatsweb web
windowrule {
    name = whatsweb-float
    match:class = chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default

    float = true
    size = 1200 800
    center = true
}

# xwayland video bridge
windowrule {
    name = xwaylandvideobridge-fix
    match:class = ^(xwaylandvideobridge)$

    opacity = 0.0 override
    no_anim = true
    no_initial_focus = true
    max_size = 1 1
    no_blur = true
    no_focus = true
}

# Apache NetBeans IDE
windowrule {
    name = netbeans-float
    match:class = ^(Apache NetBeans IDE.*)$

    float = true
    pin = false
    stay_focused = false
}
