
-- #######################################################################################
-- HYPRLAND LUA CONFIG 
-- Ref: https://wiki.hypr.land/Configuring/Start/

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 # remove this line to remove the warning


--  You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:

require("modules.monitors")
require("modules.env")
require("modules.general")
require("modules.exec")
require("modules.custom.battery")
require("modules.custom.whatsapp")
require("modules.keybinds")
require("modules.rules")
 
